
// This header is generated by script automatically

#ifndef DEPTH_ESTIMATION_MODEL_H
#define DEPTH_ESTIMATION_MODEL_H

#define MODEL_TT_DEPTH_ESTIMATION "tt_depth_estimation_v2.0.model"

#endif // DEPTH_ESTIMATION_MODEL_H
